### PR TITLE
That was quick! Here are the updates for viewonly priviledges.

### PR DESCRIPTION
**Pull request by lsetiawan**
The user has to be in a group called `readonly`, knock on wood I didn't break anything major. Also, I still need to figure out how to make a 'view only' map for Sampling Features. Thanks for creating the branch! :)

### CODE REVIEW

**Comment by miguelcleon** [comment]
Annoyingly the message about this pull request went into my clutter folder and I didn't notice it until now. Might be good to send me an extra email with these important PRs.

**Comment by miguelcleon** [comment]
Hmm, I'm just testing this out, I'm not sure if this does what we need. I think a 'view only' user should be able to go to any change list, or change form but should not be allowed to save any changes. As this is working now. They can see links to change lists but just get access forbidden messages when they click on the links. So they can't really view anything much, except for the graphing and map which can already be seen without logging in.

**Comment by lsetiawan** [comment]
@miguelcleon  You have to create a user with staff privilege and a group that has all priviledge called `readonly`

**Comment by lsetiawan** [comment]
Here's an example of permission for a user name guest.

screenshot 2016-09-27 10 09 24

**Comment by lsetiawan** [comment]
@miguelcleon Also, I just realized that now you'd have to assign each user a group, and you can't access the admin without being in a group. So, I'm going to fix this in my next PR. Sorry about that. Thanks for letting me know, also I'm going to remove save priviledge. Stay tuned.

**Comment by miguelcleon** [comment]
ok sounds good.

**Comment by miguelcleon** [comment]
yeah, when I login as myself, I can't access anything, probably because I'm not in a group, which I think is the problem you are talking about.

**Comment by miguelcleon** [comment]
When I add an admin group with all rights and add myself to the group things seem to work properly. This might be ok, but it would be better if this update looked at both user and group rights. Is that what you are thinking @lsetiawan ?

**Pull request merged**
