### PR TITLE
Added requests library to requirements.txt and odm2adminenv.yml since it was missing.

### PR DESCRIPTION
**Pull request by lsetiawan**
Requests library was missing, so it is added to requirements.txt and the odm2adminenv.yml. The odm2adminenv.yml was also updated with django-recaptcha.

### CODE REVIEW

**Comment by miguelcleon** [comment]
I was playing around with the requests library but I'm pretty sure I don't actually use it. I think I just left an import in the views.py file. Is that were you ran into it?

**Comment by miguelcleon** [comment]
django-recaptcha should be in the odm2adminenv.yml though, thank you.

**Comment by lsetiawan** [comment]
@miguelcleon yea that's what I ran into, so remove this then? Thanks

**Comment by miguelcleon** [comment]
Yes, it's not used, so we should remove it.

**Comment by lsetiawan** [comment]
@miguelcleon I see that the requests is used in this function:
``` python
def grecaptcha_verify(request):
    if request.method == 'POST':
        response = {}
        data = request.POST
        captcha_rs = data.get('g_recaptcha_response')
        url = "https://www.google.com/recaptcha/api/siteverify"
        params = {
            'secret': settings.RECAPTCHA_PRIVATE_KEY,
            'response': captcha_rs,
            'remoteip': get_client_ip(request)
        }
        verify_rs = requests.get(url, params=params, verify=True)
        verify_rs = verify_rs.json()
        response["status"] = verify_rs.get("success", False)
        response['message'] = verify_rs.get('error-codes', None) or "Unspecified error."
        return response
```

not sure if deleting the whole thing would affect how your Recaptcha operates. Thanks.

**Pull request merged**
