### PR TITLE
Fixed errors when building Docker Image & update README

### PR DESCRIPTION
**Pull request by lsetiawan**
The docker now is able to build the image, though your sample db seem to be missing samplingfeatures?

### CODE REVIEW

**Comment by miguelcleon** [comment]
Is the samplingfeatures problem the same problem with postgis the featuregeometry field?

**Comment by lsetiawan** [comment]
It seems to be missing even after I installed POSTGIS Extension.

**Comment by miguelcleon** [comment]
yeah, your right. I'll have to fix that

**Comment by miguelcleon** [comment]
@lsetiawan Ok, yes It works! but only when building the image locally, the readme direction / docker hub repository are not working and probably just need to be updated.

**Comment by miguelcleon** [comment]
@lsetiawan Ok I updated the ODM2AdminExamplePostgresqlDB with the samplingfeatures table. Do you want to give it a try, perhaps with the docker hub updated?

**Comment by lsetiawan** [comment]
might have to do another "prerelease"

**Comment by miguelcleon** [comment]
Ok, I just left the office and it doesn't seem like you can do it from a mobile, so I won't be able to do it for a few hours.

**Comment by lsetiawan** [comment]
okay, no worries! :)

**Pull request merged**
