### PR TITLE
Build and upload docs automatically

### PR DESCRIPTION
**Pull request by ocefpaf**
@lsetiawan I used the README to create the `index.rst`, no docstrings yet.

### CODE REVIEW

**Comment by lsetiawan** [comment]
I don't get why it's failing.

**Comment by ocefpaf** [comment]
> I don't get why it's failing.

What failure :wink: 

Just kidding I forgot to create an empty `gh-pages` branch. That is the only thing that `doctr` does not do automatically (yet).

**Review by lsetiawan — APPROVED** [review]
@ocefpaf has done an awesome job yet again! Merging.. Thanks so much 😄

**Comment by lsetiawan** [comment]
@ocefpaf `.nojekyll` seems to be missing, causing static files to not render. Thanks

**Comment by ocefpaf** [comment]
Thanks @lsetiawan!

Because ODM2-Admin is not an installable module we may face a few issue using the autodoc later. I'm experimenting with possible alternatives.

> @ocefpaf `.nojekyll` seems to be missing, causing static files to not render. Thanks

`doctr` should add that  :confused:, see https://github.com/drdoctr/doctr/blob/958e7360111cb19f4860cf45e5cabca5d26e59a9/doctr/travis.py#L259

Let me check...

**Comment by lsetiawan** [comment]
It works now! 👍

**Comment by ocefpaf** [comment]
> It works now! 👍 

I'm making some minor adjustments and it may disappear. It should be back online in a minute.

**Comment by miguelcleon** [comment]
So where does this end up pointing too? In the demo yesterday there was a link odm2.github.io/odm2 ? That isn't correct, I figured the link would be on here (https://github.com/ODM2/odm2-software-ecosystem) somewhere but I don't see it

**Comment by ocefpaf** [comment]
http://odm2.github.io/ODM2-Admin/

**Comment by miguelcleon** [comment]
Great thank you both!

**Pull request merged**
