### PR TITLE
doc update test

### PR DESCRIPTION
**Pull request by miguelcleon**
last PR failed on travis. It seems like that shouldn't have happened as it only contained doc updates

### CODE REVIEW

**Comment by miguelcleon** [comment]
@lsetiawan any idea why this is failing travis? It seemed like maybe it has to do with tests, but that doesn't seem to be the case.

**Comment by miguelcleon** [comment]
@lsetiawan I'm writing some tests just in case that might fix it. It is difficult to imagine writing all of the tests that it might be a good idea to have. There are just so many.

**Comment by lsetiawan** [comment]
I've restarted the job, it was a giving a file not found error, but it doesn't say what file.

**Comment by miguelcleon** [comment]
@lsetiawan ok, it has continued to do this 4th or 5th time so far, the only thing I changed in all of those cases were the documentation.

**Comment by lsetiawan** [comment]
@ocefpaf any idea why this is failing? The error we get is:

`ERROR: file not found: discover`

**Comment by miguelcleon** [comment]
@ocefpaf I added a test because it looks like it might be a problem with test discovery? I don't know but it seemed like it would be worth trying here is the branch that failed https://travis-ci.org/ODM2/ODM2-Admin/builds/312503780?utm_source=github_status&utm_medium=notification

**Comment by miguelcleon** [comment]
still failed and it didn't run the test.

**Comment by miguelcleon** [comment]
I moved the test I added which works locally but it still did not run on Travis and it exited with the same error.

**Comment by ocefpaf** [comment]
@miguelcleon and @lsetiawan the testing framework here was design for a installable package. Because #102 was never accepted we need to change the logic. See  https://github.com/ODM2/ODM2-Admin/pull/191

Note that #191 will fail b/c we must configure the django app before running the tests. I'll leave that to the  django experts :wink:

**Comment by miguelcleon** [comment]
is my .travis.yml file wrong?

**Comment by lsetiawan** [comment]
I think that #191 is the right fix to `.travis.yml` to make the tests to run. But we do need need to configure the django app.

**Comment by miguelcleon** [comment]
@lsetiawan ok, in this latest commit, I just changed the` matrix:` section, I'm not sure what else to change at the moment. I need to work on something else for a little bit.

**Comment by lsetiawan** [comment]
See https://github.com/ODM2/ODM2-Admin/pull/191/commits/12d37851dae467cb148f0f58bdcb795a547bb02a The `matrix:` shouldn't need to change.

**Comment by miguelcleon** [comment]
OK, latest commit attempts to replicate https://github.com/ODM2/ODM2-Admin/pull/191/commits/12d37851dae467cb148f0f58bdcb795a547bb02a maybe it will work

**Comment by lsetiawan** [comment]
Now the error is `OSError: libgeos-3.5.0.so: cannot open shared object file: No such file or directory` Seems to be a problem with gdal.

**Comment by miguelcleon** [comment]
The import line it is failing is from models.py line 16: 
`
from django.contrib.gis.db import models as gis_models`

**Comment by miguelcleon** [comment]
that is also the first django import line. I'm going to try moving it, to see if the next import also errors.

**Comment by lsetiawan** [comment]
Gimme a sec, lemme try this out locally.

**Comment by miguelcleon** [comment]
ok

**Comment by miguelcleon** [comment]
latest commit fails on the below, other django.db and django.core imports worked. 
`from django.contrib.gis.geos import GEOSGeometry`

**Comment by lsetiawan** [comment]
I tried this locally and getting a different error... frustrating. hmm... `django.contrib.gis.geos.error.GEOSException: Error encountered checking Geometry returned from GEOS C function "GEOSWKTReader_read_r"` I have the same exact packages as in travis.

**Comment by miguelcleon** [comment]
maybe @ocefpaf has an idea about what else to try?

**Comment by ocefpaf** [comment]
I'm away from my laptop for a few days but I'll try to take a quick look
tomorrow.

**Comment by ocefpaf** [comment]
@lsetiawan the `django` version used here is quite and inconsistent with `conda-forge`'s `gdal` and `geos`.
The options are:

- don't use `conda-forge` and try to see if there are wheels for those;
- update `django` to 2.0 where the `geos` string parsing was fixed, see https://github.com/django/django/commit/78c155cf2e5a27fd2db18c2d46953b1b0fdba829#diff-e0475de5c597e1c67bb40752a38f2276
- backport that patch to conda-forge `django >=1.10.6`

Any those will require some considered effort! My recommendation is to "future proof" the app and go for `django 2.0`. The second option would be the backport.

**Pull request closed without merging**
