### PR TITLE
add sidebar in map

### PR DESCRIPTION
**Pull request by miguelcleon**
add sidebar in map

### CODE REVIEW

**Comment by miguelcleon** [comment]
@emiliom I added the sidebar so users aren't navigated away from the map, which you have wanted for a while. I've moved these changes live on the CZIMEA instance http://odm2admin.cuahsi.org/CZIMEA/

**Comment by emiliom** [comment]
@miguelcleon Very nice, and a very pleasant, unexpected surprise!! Thanks!

I tried it out a bit. Seems to work, but also seemed very slow (the information took a while to populate or update on the sidebar).

Just out of curiosity, this PR isn't merged, but the functionality is already deployed?

**Comment by miguelcleon** [comment]
Yeah I figured I'd move the changes to your instance so you could see it before I merged.

**Comment by miguelcleon** [comment]
Yeah it is slow to load, i think it is the inline forms which seem to take along time to build.

**Pull request merged**
