### PR TITLE
Extracted settings into a YAML rather than within settings.py

### PR DESCRIPTION
**Pull request by lsetiawan**
Rewrote base.py to have the core settings and settings.py to be more customized. It seemed to work for me. Please let me know if I'm missing any settings or if some setting should stay within the python code. Thanks. This is part of the work in separating base code vs human readable settings file. [#88](https://github.com/miguelcleon/ODM2-Admin/issues/88)

### CODE REVIEW

**Comment by miguelcleon** [comment]
I'll try it out.

**Comment by lsetiawan** [comment]
Thanks! 😄

**Comment by miguelcleon** [comment]
A couple things 
pyyaml should be added to odm2adminenv and requirements.txt 
This setting should be added to settings.yaml to allow the user to specify the name of the host server for example I set mine to 
`ALLOWED_HOSTS = ['dev-odm2admin.cuahsi.org','odm2admin.cuahsi.org',]`

The below settings are needed to configure full urls, I change them for different instances. Only what is in the single quotes for each. 
`MEDIA_ROOT = '{}'.format(ROOT)`

`MEDIA_URL = '/odm2testapp/upfiles/'
`
`CUSTOM_TEMPLATE_PATH = '/admin/{}/'.format(APP_NAME)`

`URL_PATH = 'admin/'`

`STATIC_ROOT = '{}/static'.format(ROOT)`

`

**Comment by miguelcleon** [comment]
woah, that formatting got wierd, sorry I'll try to fix it. Sorry. 
That's better

**Comment by lsetiawan** [comment]
@miguelcleon I added more variables to the settings that you have suggested and added missing dependencies such as `pyyaml`. Thanks.

**Comment by miguelcleon** [comment]
Great, trying it now.

**Comment by miguelcleon** [comment]
Ok, I just needed to make one change to make it work. The ALLOWED_HOSTS setting is now checked whether or not debug is set to True. So I had to comment out the line about checking debug before setting allowed hosts.  When your developing locally in the settings.yaml file you just need:
```
Allowed Hosts:
 - 127.0.0.1  

```
Here is the Django doc about this: https://docs.djangoproject.com/en/1.10/ref/settings/#allowed-hosts

**Comment by lsetiawan** [comment]
Ah, okay! Awesome. Thank you.

**Pull request merged**
