### PR TITLE
A lot of changes, please let me know if you have any questions.

### PR DESCRIPTION
**Pull request by lsetiawan**

### CODE REVIEW

**Comment by lsetiawan** [comment]
Not sure where you wanted me to issue the pull request, I hope this is the right branch.

**Comment by miguelcleon** [comment]
playing around with it a bit, yeah alot of changes, I'm not sure why you moved settings into config.json the idea was to keep all changable application settings in settings.py and other Django settings that shouldn't change in base.py 

after playing with it for 15 minutes I can't even open the file not sure why
`
FileNotFoundError: [Errno 2] No such file or directory: './templatesAndSettings/config.json'
`
This is going to take a while to work through. Would have been better to issue smaller changes

**Comment by lsetiawan** [comment]
The Idea behind the config.json was for changing names of the applications, so that it's not limited to just have the name as 'ODM2CZOData'. Huh... that is really weird. I'm pretty sure I put that file in there..

**Comment by miguelcleon** [comment]
The file is there, I just get an error trying to load it. Maybe the naming stuff could go in settings.py? I really don't think we need 3 configuration files.

**Comment by lsetiawan** [comment]
I see, I suppose that would work. I figured that json is a little more straightforward. I guess there just need to be some documentation to help with the configurations.

**Comment by miguelcleon** [comment]
Yes, we will definitely need more documentation about this.

**Comment by miguelcleon** [comment]
great, thanks, I'm in meetings all day today but I might get a chance to take a look at this this afternoon.

**Comment by miguelcleon** [comment]
Ok, I've been able to try out a bunch of the changes, they seem great! Thanks Don! @lsetiawan I'm going to go ahead and merge them. @emiliom

**Comment by emiliom** [comment]
Awesome!

**Pull request merged**
