### PR TITLE
Update cz

### PR DESCRIPTION
**Pull request by lsetiawan**
This is a continuation of PR #136

### CODE REVIEW

**Comment by miguelcleon** [comment]
Here is the problem 
https://github.com/lsetiawan/ODM2-Admin/blob/development/odm2admin/models.py#L585

causing this to fail 
http://dev-odm2admin.cuahsi.org/ODM2-Admintest/mapdata.html

table should be `cv_datasettype`

**Comment by miguelcleon** [comment]
I changed that single line in http://dev-odm2admin.cuahsi.org/ODM2-Admintest/ 
but I don't have time to test your changes tonight, I'll look at it tomorrow.

**Comment by miguelcleon** [comment]
@lsetiawan Ok, I changed my mind, I applied the changes, it looks like it is working! 

I'll test some more tomorrow though.

**Comment by miguelcleon** [comment]
clicking around some looks right so far http://dev-odm2admin.cuahsi.org/ODM2-Admintest/mapdata.html

**Comment by miguelcleon** [comment]
It's looking good. Biggest issue I'm seeing is the map is taking a good deal longer to load then it did before, this is probably due to the number of sampling features in the LCZO database and possibly more general database performance issues.

**Comment by miguelcleon** [comment]
@lsetiawan @emiliom 

These updates have been deployed to http://dev-odm2admin.cuahsi.org/CZIMEA/ and /LCZO/ 

I noticed that the sites on both take a while to load, so we might want to consider some kind of loading indicator javascript.

**Comment by emiliom** [comment]
> These updates have been deployed to http://dev-odm2admin.cuahsi.org/CZIMEA/ and /LCZO/

Woo-hoo, thanks @miguelcleon!

> I noticed that the sites on both take a while to load, so we might want to consider some kind of loading indicator javascript.

Agreed, it's slow, and a progress/loading indicator would help.

**Comment by lsetiawan** [comment]
@miguelcleon Thanks for testing and deploying this! 😃

**Pull request merged**
