### PR TITLE
Map update, added icon labels, and filter by dataset

### PR DESCRIPTION
**Pull request by lsetiawan**
Had a little hiccup, not realizing you made changes, I had to merge after I had pushed, but all fixed now.

### CODE REVIEW

**Comment by lsetiawan** [comment]
@emiliom

**Comment by lsetiawan** [comment]
@miguelcleon I've added the filtering capabilities here, though I haven't merged your current commits.

**Comment by miguelcleon** [comment]
Ok, I tried out your changes but I get an error, looks like the file DatasetsList.html is missing? 

> TemplateDoesNotExist at /admin/mapdata.html
> DatasetsList.html

**Comment by lsetiawan** [comment]
@miguelcleon Sorry about that, totally missed that file. I've added it now. Thanks

**Comment by miguelcleon** [comment]
wow, that's fantastic! Just got home, but I think I will go ahead and merge this pull request. Maybe tomorrow. I'm a little worried about how this will look if there are a lot more datasets.

**Comment by lsetiawan** [comment]
Thank you. Can probably allow scrolling when there are more dataset. You have done so with other attributes such as results.

**Pull request closed without merging**
