### PR TITLE
error from last update in mapdata.

### PR DESCRIPTION
**Pull request by miguelcleon**

### CODE REVIEW

**Comment by miguelcleon** [comment]
fixes error when viewing excavations.

**Comment by lsetiawan** [comment]
@miguelcleon I'd like to let you know that I found errors when viewing Observation Wells. Thanks.

**Comment by miguelcleon** [comment]
your right, found it thanks.

**Comment by miguelcleon** [comment]
Ok it should be fixed now. 
[https://github.com/miguelcleon/ODM2-Admin/pull/33]

**Comment by lsetiawan** [comment]
@miguelcleon Looks good. Thanks!

**Pull request merged**
