### PR TITLE
Rebased view only feature

### PR DESCRIPTION
**Pull request by lsetiawan**
@miguelcleon This is the rebased viewonly feature. Thanks.

### CODE REVIEW

**Comment by lsetiawan** [comment]
Also an FYI Samplingfeatures still needs work for the viewonly portion seeing if I can get some sort of viewonly map and prevent changes to the point.

**Comment by lsetiawan** [comment]
@miguelcleon  I think this is okay to merge, I've already changed the featuregeometry wkt to not be able to be changed. I just don't have a read only map for a quick view, but I think this can be an enhancement for later. Thanks

**Comment by miguelcleon** [comment]
Ok, yeah, I'm not sure how practical those maps at the sampling feature view level are anyway. When I'm looking at sampling features we use, these previews are really coarse and don't show enough detail to really help.

**Comment by miguelcleon** [comment]
oh right sorry, the two conflicting files don't have any user interaction so, you should just be able to just overwrite them.

**Comment by miguelcleon** [comment]
I wanted to try this out again before pulling, but the broken functions were critical to some ongoing work.

**Comment by lsetiawan** [comment]
@miguelcleon I've merged your fixes on the broken functions and fixed the conflict, hopefully it works for you. Thanks

**Comment by miguelcleon** [comment]
Ok I have a local copy and a created a read only account but the only thing viewable from that account are the graphs and maps. Maybe I'm missing something? Last time I tried this, I could navigate the site just the fields were not editable, now with the read only account I can't navigate the site.

**Comment by lsetiawan** [comment]
@miguelcleon To create a read only account, the user has to be in `readonly` group and that group should have all access as long as the groupname is `readonly`

**Comment by lsetiawan** [comment]
screenshot 2016-11-03 13 42 37

**Comment by lsetiawan** [comment]
screenshot 2016-11-03 13 44 22

**Comment by miguelcleon** [comment]
ok yes that worked. except I can still change the location of sampling feature with the  Featuregeometrywkt field.

**Comment by miguelcleon** [comment]
maybe I haven't gotten your latest changes, let me double check.

**Comment by miguelcleon** [comment]
it is the devviewonly branch right?

**Comment by lsetiawan** [comment]
Hmm... That's weird.. because I can't change the featuregeometrywkt field. It might show that you can, but if you try to edit, you won't be able to. Also I've removed the buttons on the bottom, so no changes can occur either way.

**Comment by miguelcleon** [comment]
ok yes it works, I hadn't pulled the latest changes.

**Pull request merged**
